# TODO: Only run on specific labels https://stackoverflow.com/questions/62325286/run-github-actions-when-pull-requests-have-a-specific-label
name: Assign Project Fields Based on Labels

on:
  issues:
    types: [labeled, unlabeled, opened]

jobs:
  update-project:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: read
      repository-projects: write


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update project fields based on labels
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          # TODO: Remove
          gh auth status
          
          ISSUE_NUMBER=${{ github.event.issue.number }}
          # Static IDs fetched using GH GraphQL API
          PROJECT_ID=PVT_kwDOAaM4rc4Al8Zm
          # "Priority" field
          FIELD_ID=PVTSSF_lADOAaM4rc4Al8Zmzgd61_0
          # "P0" option
          P0_OPT_ID=25973b1f
          
          # Use this repo for all commands
          gh repo set-default ${{ github.repository }}
          
          # Fetch available labels
          LABELS=$(gh issue view $ISSUE_NUMBER --json labels --jq '.labels[].name')

          ISSUE_ID=$(gh issue view $ISSUE_NUMBER --json id --jq '.id')
          
          # Define your label to project field mappings
          if echo "$LABELS" | grep -q "Priority: P0"; then
              gh api graphql -f query="mutation {
                updateProjectV2ItemFieldValue(
                  input: {
                    projectId: \"$PROJECT_ID\",
                    itemId: \"$ISSUE_ID\",
                    fieldId: \"$FIELD_ID\",
                    value: {singleSelectOptionId: \"$P0_OPT_ID\"}
                  }
                ){
                projectV2Item {
                  id
                }
                }
              }"
          fi
